- hosts: 192.168.33.10
  tasks:
    - name: installation apache
      package:
       name: 
         - httpd
         - git
       state: present
       
    - name: lancer apache
      service:
        name:
          - httpd
        state: started
        enabled: true
        
    
